alias ~='cd ~'
alias ll='ls -la'
alias gs='git status'
alias gp='git push'
alias gl='git log'
alias gll='git log --oneline --all --graph --decorate  $*'
alias gpd='git pull origin develop'
alias grd='git pull --rebase origin develop'