.SILENT:

include ../setup.mk

TARGET_CONFIG_DIRECTORY := "$$HOME/.config"

install:
	make install-config-files TARGET_CONFIG_DIRECTORY="$(TARGET_CONFIG_DIRECTORY)"

extract:
	make extract-config-files TARGET_CONFIG_DIRECTORY="$(TARGET_CONFIG_DIRECTORY)"
